import 'package:flutter/material.dart';
import 'dart:math' as math;

import '../physics/collider_shape.dart' as physics;
import '../physics/vector3.dart';

/// One vertex in a procedural textured mesh prototype.
///
/// Filament represents a renderable mesh as vertex/index buffers plus material
/// data. This Dart prototype mirrors that shape so the API can be explored
/// before native buffer upload is wired in.
final class MeshVertex {
  const MeshVertex({
    required this.position,
    required this.uv,
    this.normal = const Vector3(0, 1, 0),
  });

  /// Local-space vertex position.
  final Vector3 position;

  /// Local-space unit normal used by lit materials.
  final Vector3 normal;

  /// Texture coordinate in normalized UV space.
  final Offset uv;

  Map<String, Object> toMessage() => {
    'x': position.x,
    'y': position.y,
    'z': position.z,
    'nx': normal.x,
    'ny': normal.y,
    'nz': normal.z,
    'u': uv.dx,
    'v': uv.dy,
  };
}

/// Small texture description used by [TexturedMeshPrototype].
final class MeshTexturePrototype {
  const MeshTexturePrototype({
    required this.primaryColor,
    required this.secondaryColor,
    this.repeatU = 1,
    this.repeatV = 1,
  }) : kind = MeshTextureKind.checker,
       assetPath = null,
       sourceRegion = null,
       assert(repeatU > 0),
       assert(repeatV > 0);

  const MeshTexturePrototype.asset({
    required this.assetPath,
    this.sourceRegion,
    this.repeatU = 1,
    this.repeatV = 1,
    this.primaryColor = const Color(0xff14b8a6),
    this.secondaryColor = const Color(0xfff8fafc),
  }) : assert(repeatU > 0),
       assert(repeatV > 0),
       kind = MeshTextureKind.asset;

  final MeshTextureKind kind;
  final String? assetPath;
  final MeshTextureRegion? sourceRegion;

  final Color primaryColor;
  final Color secondaryColor;
  final double repeatU;
  final double repeatV;

  Map<String, Object?> toMessage() => {
    'kind': kind.name,
    'primaryColor': primaryColor.toARGB32(),
    'secondaryColor': secondaryColor.toARGB32(),
    'repeatU': repeatU,
    'repeatV': repeatV,
    ...?(assetPath == null ? null : {'assetPath': assetPath}),
    ...?(sourceRegion == null
        ? null
        : {'sourceRegion': sourceRegion!.toMessage()}),
  };
}

enum MeshTextureKind { checker, asset }

/// Rectangle inside an atlas texture, in normalized image coordinates.
final class MeshTextureRegion {
  const MeshTextureRegion({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  }) : assert(left >= 0 && left < right && right <= 1),
       assert(top >= 0 && top < bottom && bottom <= 1);

  /// Creates a normalized region from pixel coordinates.
  factory MeshTextureRegion.pixels({
    required double imageWidth,
    required double imageHeight,
    required double x,
    required double y,
    required double width,
    required double height,
  }) {
    return MeshTextureRegion(
      left: x / imageWidth,
      top: y / imageHeight,
      right: (x + width) / imageWidth,
      bottom: (y + height) / imageHeight,
    );
  }

  final double left;
  final double top;
  final double right;
  final double bottom;

  Map<String, Object> toMessage() => {
    'left': left,
    'top': top,
    'right': right,
    'bottom': bottom,
  };
}

/// Link to a custom Filament material shader.
///
/// [sourceAssetPath] may point to a human-authored `.mat` file or a project
/// `.shader` alias. Filament runtime loads [filamatAssetPath], the compiled
/// `.filamat` output generated by Android build tooling or supplied directly.
final class MaterialShaderPrototype {
  factory MaterialShaderPrototype({
    required String sourceAssetPath,
    String? filamatAssetPath,
    List<MaterialShaderUniform> uniforms = const [],
  }) {
    assert(
      sourceAssetPath.endsWith('.mat') || sourceAssetPath.endsWith('.shader'),
    );
    final compiledAssetPath =
        filamatAssetPath ?? _compiledFilamatPath(sourceAssetPath);
    assert(compiledAssetPath.endsWith('.filamat'));
    return MaterialShaderPrototype._(
      sourceAssetPath: sourceAssetPath,
      filamatAssetPath: compiledAssetPath,
      uniforms: uniforms,
    );
  }

  factory MaterialShaderPrototype.compiled({
    required String filamatAssetPath,
    List<MaterialShaderUniform> uniforms = const [],
  }) {
    assert(filamatAssetPath.endsWith('.filamat'));
    return MaterialShaderPrototype._(
      sourceAssetPath: null,
      filamatAssetPath: filamatAssetPath,
      uniforms: uniforms,
    );
  }

  const MaterialShaderPrototype._({
    required this.sourceAssetPath,
    required this.filamatAssetPath,
    required this.uniforms,
  });

  final String? sourceAssetPath;
  final String filamatAssetPath;
  final List<MaterialShaderUniform> uniforms;

  Map<String, Object?> toMessage() {
    final message = <String, Object?>{
      'filamatAssetPath': filamatAssetPath,
      'uniforms': [for (final uniform in uniforms) uniform.toMessage()],
    };
    final sourceAssetPath = this.sourceAssetPath;
    if (sourceAssetPath != null) {
      message['sourceAssetPath'] = sourceAssetPath;
    }
    return message;
  }
}

String _compiledFilamatPath(String sourceAssetPath) {
  final extensionIndex = sourceAssetPath.lastIndexOf('.');
  assert(extensionIndex > 0);
  return '${sourceAssetPath.substring(0, extensionIndex)}.filamat';
}

/// Initial value for a custom material parameter/uniform.
final class MaterialShaderUniform {
  const MaterialShaderUniform._({
    required this.name,
    required this.type,
    required this.value,
  });

  factory MaterialShaderUniform.float(String name, double value) {
    return MaterialShaderUniform._(
      name: name,
      type: MaterialShaderUniformType.float,
      value: value,
    );
  }

  factory MaterialShaderUniform.bool(String name, bool value) {
    return MaterialShaderUniform._(
      name: name,
      type: MaterialShaderUniformType.bool,
      value: value,
    );
  }

  factory MaterialShaderUniform.color(String name, Color value) {
    return MaterialShaderUniform._(
      name: name,
      type: MaterialShaderUniformType.color,
      value: value.toARGB32(),
    );
  }

  final String name;
  final MaterialShaderUniformType type;
  final Object value;

  Map<String, Object> toMessage() => {
    'name': name,
    'type': type.name,
    'value': value,
  };
}

enum MaterialShaderUniformType { float, bool, color }

/// Material settings for a procedural mesh.
///
/// Filament material source files use `.mat`, but Android renders the compiled
/// `.filamat` output. Keep both paths so build tooling can compile the source
/// while runtime code loads the compiled material.
final class MeshMaterialPrototype {
  const MeshMaterialPrototype._({
    required this.kind,
    required this.baseColor,
    required this.metallicFactor,
    required this.roughnessFactor,
    required this.doubleSided,
    this.texture,
    this.textureUniforms = const {},
    this.shader,
    this.matAssetPath,
    this.filamatAssetPath,
  });

  /// Uses a generated checker texture packed into the temporary GLB mesh.
  factory MeshMaterialPrototype.checker(
    MeshTexturePrototype texture, {
    Color baseColor = Colors.white,
    double metallicFactor = 0,
    double roughnessFactor = 0.85,
    bool doubleSided = true,
  }) {
    assert(metallicFactor >= 0 && metallicFactor <= 1);
    assert(roughnessFactor >= 0 && roughnessFactor <= 1);
    return MeshMaterialPrototype._(
      kind: MeshMaterialKind.checker,
      texture: texture,
      baseColor: baseColor,
      metallicFactor: metallicFactor,
      roughnessFactor: roughnessFactor,
      doubleSided: doubleSided,
    );
  }

  factory MeshMaterialPrototype.shader({
    required MaterialShaderPrototype shader,
    MeshTexturePrototype? texture,
    Map<String, MeshTexturePrototype> textureUniforms = const {},
    Color baseColor = Colors.white,
    double metallicFactor = 0,
    double roughnessFactor = 0.85,
    bool doubleSided = true,
  }) {
    assert(metallicFactor >= 0 && metallicFactor <= 1);
    assert(roughnessFactor >= 0 && roughnessFactor <= 1);
    return MeshMaterialPrototype._(
      kind: MeshMaterialKind.shader,
      shader: shader,
      texture: texture,
      textureUniforms: textureUniforms,
      matAssetPath: shader.sourceAssetPath?.endsWith('.mat') == true
          ? shader.sourceAssetPath
          : null,
      filamatAssetPath: shader.filamatAssetPath,
      baseColor: baseColor,
      metallicFactor: metallicFactor,
      roughnessFactor: roughnessFactor,
      doubleSided: doubleSided,
    );
  }

  /// Uses a Filament `.mat` source and its compiled `.filamat` runtime asset.
  factory MeshMaterialPrototype.filamentSource({
    required String matAssetPath,
    String? filamatAssetPath,
    Map<String, MeshTexturePrototype> textureUniforms = const {},
    Color baseColor = Colors.white,
    double metallicFactor = 0,
    double roughnessFactor = 0.85,
    bool doubleSided = true,
  }) {
    assert(matAssetPath.endsWith('.mat'));
    final compiledAssetPath =
        filamatAssetPath ?? _compiledFilamatPath(matAssetPath);
    assert(compiledAssetPath.endsWith('.filamat'));
    assert(metallicFactor >= 0 && metallicFactor <= 1);
    assert(roughnessFactor >= 0 && roughnessFactor <= 1);
    final shader = MaterialShaderPrototype(
      sourceAssetPath: matAssetPath,
      filamatAssetPath: compiledAssetPath,
    );
    return MeshMaterialPrototype._(
      kind: MeshMaterialKind.filamentSource,
      shader: shader,
      matAssetPath: matAssetPath,
      filamatAssetPath: compiledAssetPath,
      textureUniforms: textureUniforms,
      baseColor: baseColor,
      metallicFactor: metallicFactor,
      roughnessFactor: roughnessFactor,
      doubleSided: doubleSided,
    );
  }

  factory MeshMaterialPrototype.shaderSource({
    required String shaderAssetPath,
    String? filamatAssetPath,
    MeshTexturePrototype? texture,
    Map<String, MeshTexturePrototype> textureUniforms = const {},
    Color baseColor = Colors.white,
    double metallicFactor = 0,
    double roughnessFactor = 0.85,
    bool doubleSided = true,
    List<MaterialShaderUniform> uniforms = const [],
  }) {
    return MeshMaterialPrototype.shader(
      shader: MaterialShaderPrototype(
        sourceAssetPath: shaderAssetPath,
        filamatAssetPath: filamatAssetPath,
        uniforms: uniforms,
      ),
      texture: texture,
      textureUniforms: textureUniforms,
      baseColor: baseColor,
      metallicFactor: metallicFactor,
      roughnessFactor: roughnessFactor,
      doubleSided: doubleSided,
    );
  }

  factory MeshMaterialPrototype.filamat({
    required String assetPath,
    MeshTexturePrototype? texture,
    Map<String, MeshTexturePrototype> textureUniforms = const {},
    Color baseColor = Colors.white,
    double metallicFactor = 0,
    double roughnessFactor = 0.85,
    bool doubleSided = true,
    List<MaterialShaderUniform> uniforms = const [],
  }) {
    assert(assetPath.endsWith('.filamat'));
    return MeshMaterialPrototype.shader(
      shader: MaterialShaderPrototype.compiled(
        filamatAssetPath: assetPath,
        uniforms: uniforms,
      ),
      texture: texture,
      textureUniforms: textureUniforms,
      baseColor: baseColor,
      metallicFactor: metallicFactor,
      roughnessFactor: roughnessFactor,
      doubleSided: doubleSided,
    );
  }

  final MeshMaterialKind kind;
  final Color baseColor;
  final double metallicFactor;
  final double roughnessFactor;
  final bool doubleSided;
  final MeshTexturePrototype? texture;
  final Map<String, MeshTexturePrototype> textureUniforms;
  final MaterialShaderPrototype? shader;
  final String? matAssetPath;
  final String? filamatAssetPath;

  MeshTexturePrototype get previewTexture =>
      texture ??
      const MeshTexturePrototype(
        primaryColor: Color(0xff14b8a6),
        secondaryColor: Color(0xfff8fafc),
        repeatU: 6,
        repeatV: 4,
      );

  Map<String, Object?> toMessage() {
    final message = <String, Object?>{
      'kind': kind.name,
      'baseColor': baseColor.toARGB32(),
      'metallicFactor': metallicFactor,
      'roughnessFactor': roughnessFactor,
      'doubleSided': doubleSided,
    };
    final texture = this.texture;
    if (texture != null) {
      message['texture'] = texture.toMessage();
    }
    if (textureUniforms.isNotEmpty) {
      message['textureUniforms'] = {
        for (final MapEntry(:key, :value) in textureUniforms.entries)
          key: value.toMessage(),
      };
    }
    final shader = this.shader;
    if (shader != null) {
      message['shader'] = shader.toMessage();
    }
    final matAssetPath = this.matAssetPath;
    if (matAssetPath != null) {
      message['matAssetPath'] = matAssetPath;
    }
    final filamatAssetPath = this.filamatAssetPath;
    if (filamatAssetPath != null) {
      message['filamatAssetPath'] = filamatAssetPath;
    }
    return message;
  }
}

enum MeshMaterialKind { checker, filamentSource, shader }

/// Optional physics collider attached to a procedural mesh description.
///
/// The current Jolt bridge supports [physics.BoxShape] immediately. Full triangle mesh
/// collision is represented here as API shape and can be wired to Jolt
/// `MeshShape` when the FFI layer grows that constructor.
final class MeshColliderPrototype {
  const MeshColliderPrototype._({
    required this.enabled,
    required this.kind,
    this.staticBoxShape,
  });

  const MeshColliderPrototype.disabled()
    : this._(enabled: false, kind: MeshColliderKind.none);

  const MeshColliderPrototype.staticBox(physics.BoxShape shape)
    : this._(
        enabled: true,
        kind: MeshColliderKind.staticBox,
        staticBoxShape: shape,
      );

  const MeshColliderPrototype.meshShape()
    : this._(enabled: true, kind: MeshColliderKind.meshShape);

  final bool enabled;
  final MeshColliderKind kind;
  final physics.BoxShape? staticBoxShape;

  Map<String, Object?> toMessage() => {
    'enabled': enabled,
    'kind': kind.name,
    if (staticBoxShape case final shape?)
      'staticBox': {
        'halfWidth': shape.halfWidth,
        'halfHeight': shape.halfHeight,
        'halfDepth': shape.halfDepth,
      },
  };
}

enum MeshColliderKind { none, staticBox, meshShape }

/// Height values used to generate a terrain mesh.
final class MeshHeightMap {
  const MeshHeightMap.samples({
    required this.columns,
    required this.rows,
    required this.values,
    this.heightScale = 1,
  }) : assert(columns >= 2),
       assert(rows >= 2),
       assert(values.length == columns * rows);

  /// Preview heightmap useful while image decoding is handled by native code.
  factory MeshHeightMap.wave({
    required int columns,
    required int rows,
    double heightScale = 1,
    double frequency = 2.5,
  }) {
    final values = <double>[];
    for (var row = 0; row < rows; row++) {
      final z = row / (rows - 1);
      for (var column = 0; column < columns; column++) {
        final x = column / (columns - 1);
        final height =
            0.5 +
            0.25 * math.sin(x * math.pi * frequency) +
            0.25 * math.cos(z * math.pi * frequency);
        values.add(height.clamp(0, 1).toDouble());
      }
    }
    return MeshHeightMap.samples(
      columns: columns,
      rows: rows,
      values: values,
      heightScale: heightScale,
    );
  }

  final int columns;
  final int rows;
  final List<double> values;
  final double heightScale;

  double heightAt(int column, int row) {
    return values[row * columns + column] * heightScale;
  }
}

/// Procedural mesh prototype with UVs and a lightweight texture pattern.
final class TexturedMeshPrototype {
  const TexturedMeshPrototype({
    required this.vertices,
    required this.indices,
    required this.material,
    this.collider = const MeshColliderPrototype.disabled(),
  }) : assert(indices.length % 3 == 0);

  /// Creates a rectangular mesh made of two triangles.
  factory TexturedMeshPrototype.plane({
    double width = 3,
    double depth = 2,
    MeshTexturePrototype texture = const MeshTexturePrototype(
      primaryColor: Color(0xff14b8a6),
      secondaryColor: Color(0xfff8fafc),
      repeatU: 6,
      repeatV: 4,
    ),
    MeshMaterialPrototype? material,
    MeshColliderPrototype collider = const MeshColliderPrototype.disabled(),
  }) {
    final halfWidth = width / 2;
    final halfDepth = depth / 2;
    final uSegments = texture.repeatU.ceil().clamp(1, 128).toInt();
    final vSegments = texture.repeatV.ceil().clamp(1, 128).toInt();
    final vertices = <MeshVertex>[];
    for (var v = 0; v <= vSegments; v++) {
      final tv = v / vSegments;
      for (var u = 0; u <= uSegments; u++) {
        final tu = u / uSegments;
        vertices.add(
          MeshVertex(
            position: Vector3(
              -halfWidth + width * tu,
              0,
              -halfDepth + depth * tv,
            ),
            uv: Offset(tu, tv),
          ),
        );
      }
    }
    final indices = <int>[];
    for (var v = 0; v < vSegments; v++) {
      for (var u = 0; u < uSegments; u++) {
        final topLeft = v * (uSegments + 1) + u;
        final topRight = topLeft + 1;
        final bottomLeft = topLeft + uSegments + 1;
        final bottomRight = bottomLeft + 1;
        indices.addAll([
          topLeft,
          topRight,
          bottomRight,
          topLeft,
          bottomRight,
          bottomLeft,
        ]);
      }
    }
    return TexturedMeshPrototype(
      vertices: vertices,
      indices: indices,
      material: material ?? MeshMaterialPrototype.checker(texture),
      collider: collider,
    );
  }

  /// Creates a terrain grid from height samples and recalculated normals.
  factory TexturedMeshPrototype.terrain({
    required double width,
    required double depth,
    required MeshHeightMap heightMap,
    MeshTexturePrototype texture = const MeshTexturePrototype(
      primaryColor: Color(0xff14b8a6),
      secondaryColor: Color(0xfff8fafc),
      repeatU: 6,
      repeatV: 4,
    ),
    MeshMaterialPrototype? material,
    MeshNormalMode normalMode = MeshNormalMode.recalculate,
    MeshColliderPrototype collider = const MeshColliderPrototype.disabled(),
  }) {
    final halfWidth = width / 2;
    final halfDepth = depth / 2;
    final positions = <Vector3>[];
    for (var row = 0; row < heightMap.rows; row++) {
      final v = row / (heightMap.rows - 1);
      for (var column = 0; column < heightMap.columns; column++) {
        final u = column / (heightMap.columns - 1);
        positions.add(
          Vector3(
            -halfWidth + width * u,
            heightMap.heightAt(column, row),
            -halfDepth + depth * v,
          ),
        );
      }
    }
    final indices = <int>[];
    for (var row = 0; row < heightMap.rows - 1; row++) {
      for (var column = 0; column < heightMap.columns - 1; column++) {
        final topLeft = row * heightMap.columns + column;
        final topRight = topLeft + 1;
        final bottomLeft = topLeft + heightMap.columns;
        final bottomRight = bottomLeft + 1;
        indices.addAll([
          topLeft,
          topRight,
          bottomRight,
          topLeft,
          bottomRight,
          bottomLeft,
        ]);
      }
    }
    final normals = normalMode == MeshNormalMode.recalculate
        ? _recalculateNormals(positions, indices)
        : List<Vector3>.filled(positions.length, const Vector3(0, 1, 0));
    final vertices = <MeshVertex>[];
    for (var row = 0; row < heightMap.rows; row++) {
      final v = row / (heightMap.rows - 1) * texture.repeatV;
      for (var column = 0; column < heightMap.columns; column++) {
        final index = row * heightMap.columns + column;
        final u = column / (heightMap.columns - 1) * texture.repeatU;
        vertices.add(
          MeshVertex(
            position: positions[index],
            normal: normals[index],
            uv: Offset(u, v),
          ),
        );
      }
    }
    return TexturedMeshPrototype(
      vertices: vertices,
      indices: indices,
      material: material ?? MeshMaterialPrototype.checker(texture),
      collider: collider,
    );
  }

  final List<MeshVertex> vertices;
  final List<int> indices;
  final MeshMaterialPrototype material;
  final MeshColliderPrototype collider;

  MeshTexturePrototype get texture => material.previewTexture;

  Map<String, Object> toMessage() => {
    'vertices': [for (final vertex in vertices) vertex.toMessage()],
    'indices': indices,
    'texture': texture.toMessage(),
    'material': material.toMessage(),
    'collider': collider.toMessage(),
  };
}

enum MeshNormalMode { flatUp, recalculate }

List<Vector3> _recalculateNormals(List<Vector3> positions, List<int> indices) {
  final accumulated = List<Vector3>.filled(positions.length, Vector3.zero);
  for (var i = 0; i < indices.length; i += 3) {
    final aIndex = indices[i];
    final bIndex = indices[i + 1];
    final cIndex = indices[i + 2];
    final a = positions[aIndex];
    final b = positions[bIndex];
    final c = positions[cIndex];
    final normal = _cross(_subtract(c, a), _subtract(b, a));
    accumulated[aIndex] = _add(accumulated[aIndex], normal);
    accumulated[bIndex] = _add(accumulated[bIndex], normal);
    accumulated[cIndex] = _add(accumulated[cIndex], normal);
  }
  return [for (final normal in accumulated) _normalize(normal)];
}

Vector3 _subtract(Vector3 a, Vector3 b) =>
    Vector3(a.x - b.x, a.y - b.y, a.z - b.z);

Vector3 _add(Vector3 a, Vector3 b) => Vector3(a.x + b.x, a.y + b.y, a.z + b.z);

Vector3 _cross(Vector3 a, Vector3 b) => Vector3(
  a.y * b.z - a.z * b.y,
  a.z * b.x - a.x * b.z,
  a.x * b.y - a.y * b.x,
);

Vector3 _normalize(Vector3 vector) {
  final length = math.sqrt(
    vector.x * vector.x + vector.y * vector.y + vector.z * vector.z,
  );
  if (length == 0) {
    return const Vector3(0, 1, 0);
  }
  return Vector3(vector.x / length, vector.y / length, vector.z / length);
}
